set -g terminal "tmux-256color"
set -g prefix C-s
set -g mouse on
set -g base-index 1

set-window-option -g xterm-keys on
set -s escape-time 0

set -g allow-passthrough on
set -ga terminal-features "*:hyperlinks"
set -ag terminal-overrides ",xterm-256color:RGB"
set -ga terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'

unbind -n C-h
bind -n C-Left send-keys Escape "[1;5D"
bind -n C-Right send-keys Escape "[1;5C"

set -g window-style "bg=default"
set -g window-active-style "bg=default"
set -g pane-border-style "bg=default"
set -g pane-active-border-style "bg=default"

set -g @plugin "tmux-plugins/tpm"
set -g @plugin "christoomey/vim-tmux-navigator"
set -g @plugin "tmux-plugins/tmux-yank"
set -g @plugin "tmux-plugins/tmux-cpu"

set -g @cpu_percentage_format "%3.0f%%"
set -g @ram_percentage_format "%3.0f%%"
set -g @yank_action "copy-pipe-and-cancel"

cyberdream_fg="#ffffff"
cyberdream_blue="#5ea1ff"
cyberdream_cyan="#5ef1ff"
cyberdream_green="#5eff6c"
cyberdream_purple="#bd5eff"
cyberdream_grey="#7b8496"
cyberdream_bg_highlight="#3c4048"

set -g status-style "bg=default,fg=$cyberdream_fg"
set -g status-left-length 100
set -g status-right-length 100
set -g status-position bottom
set -g status-justify left
set -g status-left "#[fg=$cyberdream_blue,bold] #S #[fg=$cyberdream_grey]│ "
set -g status-right "#[fg=$cyberdream_grey]#(cd #{pane_current_path}; git rev-parse --abbrev-ref HEAD 2>/dev/null | sed 's/^/ /' | sed 's/$/ │/')#[fg=$cyberdream_grey]CPU:#[fg=$cyberdream_green]#(iostat -c 1 2 | grep -A 1 'avg-cpu' | tail -1 | awk '{printf \"%.0f%%\", 100-$6}') #[fg=$cyberdream_grey]RAM:#[fg=$cyberdream_cyan]#(free -h | awk '/^Mem:/ {print $3\"/\"$2}') #[fg=$cyberdream_grey]│ #[fg=$cyberdream_purple]%H:%M #[fg=$cyberdream_grey]%a %d"

set -g window-status-format "#[fg=$cyberdream_grey] #I:#W "
set -g window-status-current-format "#[fg=$cyberdream_blue,bold] #I:#W "
set -g window-status-separator ""
set -g pane-border-style "fg=$cyberdream_bg_highlight"
set -g pane-active-border-style "fg=$cyberdream_blue"
set -g message-style "bg=$cyberdream_bg_highlight,fg=$cyberdream_cyan"
set -g message-command-style "bg=$cyberdream_bg_highlight,fg=$cyberdream_cyan"

unbind %
bind = split-window -h
unbind '"'
bind - split-window -v

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
bind -r m resize-pane -Z

set-window-option -g mode-keys vi
bind u copy-mode
bind v copy-mode
bind -n S-PageUp copy-mode -u

bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e'"

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi C-u send-keys -X halfpage-up
bind-key -T copy-mode-vi C-d send-keys -X halfpage-down

run '~/.tmux/plugins/tpm/tpm'
